# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_mins_cpp <- function(x, n) {
    .Call(`_mvInterp_which_mins_cpp`, x, n)
}

subsetEqual_cpp <- function(x, xGrid, dimension) {
    .Call(`_mvInterp_subsetEqual_cpp`, x, xGrid, dimension)
}

subsetNearestPoints_cpp <- function(x, xGrid, dimension) {
    .Call(`_mvInterp_subsetNearestPoints_cpp`, x, xGrid, dimension)
}

uniqueGridPoints_cpp <- function(xGrid, dimension) {
    .Call(`_mvInterp_uniqueGridPoints_cpp`, xGrid, dimension)
}

uvInterpConstant_cpp <- function(x, xGrid, yGrid, lowerBound, returnValue) {
    .Call(`_mvInterp_uvInterpConstant_cpp`, x, xGrid, yGrid, lowerBound, returnValue)
}

mvInterpConstant_cpp <- function(x, xGrid, yGrid, dimension, lowerBound) {
    .Call(`_mvInterp_mvInterpConstant_cpp`, x, xGrid, yGrid, dimension, lowerBound)
}

mvInterpConstant_fast_cpp <- function(x, xGrid, yGrid, dimension, lowerBound) {
    .Call(`_mvInterp_mvInterpConstant_fast_cpp`, x, xGrid, yGrid, dimension, lowerBound)
}

uvInterpLinear_cpp <- function(x, xGrid, yGrid) {
    .Call(`_mvInterp_uvInterpLinear_cpp`, x, xGrid, yGrid)
}

mvInterpLinear_cpp <- function(x, xGrid, yGrid, dimension) {
    .Call(`_mvInterp_mvInterpLinear_cpp`, x, xGrid, yGrid, dimension)
}

mvInterpLinear_fast_cpp <- function(x, xGrid, yGrid, dimension) {
    .Call(`_mvInterp_mvInterpLinear_fast_cpp`, x, xGrid, yGrid, dimension)
}

